# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        sudo apt-get update
        python -m pip install --upgrade pip
        pip install pylint
        sudo apt-get install xvfb libfontconfig wkhtmltopdf
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with pylint
      run: |
        pylint cogs
    - name: Create env file
      run: |
        cat << EOF > .env
        DATABASE_URL=${{ secrets.DATABASE_URL }}
        CALENDAR_ID=${{ secrets.CALENDAR_ID }}
        CALENDAR_PATH=${{ secrets.CALENDAR_PATH }}
        CALENDAR_ICS=${{ secrets.CALENDAR_ICS }}
        EOF
    - name: Test with pytest
      run: pytest --tb=line
    - name: Generate coverage
      run:  pytest --tb=line --cov-config=.coveragerc --cov --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
